### ISSUE TITLE
Infringement?

### ISSUE THREAD

**Issue by joshmn** [dvanderbeek/leather#17]
Login page looks like it's from http://wrapbootstrap.com/preview/WB0K176S9

**Comment by dvanderbeek** [comment]
It's definitely inspired by that, and was mainly meant as a starting point since that probably wouldn't match most designs without heavy modification. The css and html are all from scratch. If there's an issue it can be redesigned - do you have any resources to consult regarding whether or not that is necessary?

**Comment by dvanderbeek** [comment]
@joshmn Updated the design and removed some other photos that were only supposed to be temporary placeholders. How'd you find this gem btw?
